import { read, money, shell, status } from './core.js';
const data = read();
const products = data.products;
const totalStock = products.reduce((sum, product) => sum + Number(product.stock), 0);
const totalValue = products.reduce((sum, product) => sum + product.stock * product.cost, 0);
const low = products.filter(product => product.stock > 0 && product.stock <= product.min);
const out = products.filter(product => product.stock === 0);
const card = (label, value, detail, tone = 'up') => `<article class="card kpi"><div class="kpi-top"><span>${label}</span><i class="kpi-icon">▣</i></div><div class="value">${value}</div><div class="trend"><span class="${tone}">${tone === 'up' ? '↗' : '↘'} ${detail}</span> this month</div></article>`;
shell('dashboard', 'Dashboard', 'Your inventory performance at a glance.', `<section class="kpis">${card('Total products', products.length, '8.2%')}${card('Total stock quantity', totalStock.toLocaleString(), '2.1%')}${card('Stock valuation', money(totalValue), '14.2%')}${card('Low stock alerts', low.length, 'Requires review', 'down')}${card('Out of stock', out.length, 'Restock now', 'down')}${card('Total sales', money(data.sales.reduce((sum, sale) => sum + sale.total, 0)), '22.4%')}${card('Purchase spend', money(data.purchases.reduce((sum, item) => sum + item.total, 0)), '3.1%', 'down')}${card('Gross profit', money(data.sales.reduce((sum, sale) => sum + sale.total * .38, 0)), '12.8%')}</section><section class="dashboard-grid"><article class="card"><div class="card-header"><div><div class="card-title">Revenue & procurement velocity</div><div class="card-subtitle">Sales revenue and inventory movement trend</div></div></div><div class="chart"><div class="chart-lines"><svg viewBox="0 0 600 150" preserveAspectRatio="none"><path d="M0 122 C60 85,100 92,150 72 S240 100,300 78 S390 58,450 35 S540 15,600 28" fill="none" stroke="#4f46e5" stroke-width="4"/><path d="M0 135 C70 115,130 91,200 97 S300 83,370 75 S480 53,600 71" fill="none" stroke="#087784" stroke-width="3"/></svg></div><div class="chart-labels"><span>Week 32</span><span>Week 34</span><span>Week 36</span><span>Week 38</span><span>Today</span></div></div></article><article class="card"><div class="card-header"><div><div class="card-title">Low stock alert</div><div class="card-subtitle">Items requiring action</div></div><a href="low-stock.html">View all</a></div><div class="list-card">${[...low, ...out].map(product => `<div class="list-row"><div class="product-image">▣</div><div class="grow"><b>${product.name}</b><div class="small">${product.sku} · minimum ${product.min}</div></div>${status(product.stock ? 'Low Stock' : 'Out of Stock')}</div>`).join('') || '<div class="empty">All inventory is healthy.</div>'}</div></article></section>`);
